version: '2'

volumes:
  database_data:
    driver: local

services:
  web:
    build: .
    ports:
      - 3000:80
    links:
      - mysql
    volumes:
      - ./web:/app/web
    env_file:
      - web/secrets/secrets.env
    environment:
      SQL_URL: 'mysql://user:secret@mysql/relay-server'
      NODE_ENV: 'dev'
  
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: relay-server
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
